### ISSUE TITLE
Organization-wide configuration

### ISSUE THREAD

**Issue by smola** [dcoapp/app#93]
It would be great to be able to do more fine-grained organization-wide configuration, such as being able to set default value for `require_signoff_for_members` https://github.com/probot/dco/pull/52

**Comment by hiimbex** [comment]
Totally 👍 for this! Any interest in implementing it @smola?

**Comment by smola** [comment]
@hiimbex I have no bandwidth for this at the moment, sorry!

**Comment by davidkarlsen** [comment]
@smola any pointers to where and how this should be implemented? I could try a PR?

**Comment by gr2m** [comment]
Probot supports organization-wide configuration out-of-the-box. You can create a `.github/dco` file in the organization's `.github` repository, are use the `_extends` option, see https://probot.github.io/docs/best-practices/#store-configuration-in-the-repository

loading the configuration is taking place here:
 https://github.com/probot/dco/blob/6f7272e0b1e31ea3f82fa06d65a49f47ffd54223/index.js#L17-L22

If you like to send a pull request, please also add a test for the new functionality
